### ISSUE TITLE
ETA on da bot?

### ISSUE THREAD

**Issue by GrandMoff100** [ImDaRealAni/ani-lifelog#4]
How soon can we expect the bot to be ready again? Also what language are you writing it in?

**Comment by ImDaRealAni** [comment]
No ETA. The bot isn't really going to do much anyway except display a custom status. I'll probably only leave it on whenever I'm just idling on my computer. The bot is written in C++, but I might just rewrite it in Go.

**Comment by GrandMoff100** [comment]
Very cool
