### ISSUE TITLE
Torque

### ISSUE THREAD

**Issue by ImDaRealAni** [ImDaRealAni/ani-lifelog#5]
Tell me how they respond when you send them this: https://github.com/ImDaRealAni/ani-lifelog#52421

**Comment by ImDaRealAni** [comment]
Message has been sent.

**Comment by ImDaRealAni** [comment]
Message has been sent.

**Comment by GrandMoff100** [comment]
Yeah it went down pretty well :D they were like "how did you know?!?! But thanks anyway 😋"

**Comment by ImDaRealAni** [comment]
they were like "how did you know?!?! But thanks anyway 😋"

I remember everything.

**Comment by ImDaRealAni** [comment]
> they were like "how did you know?!?! But thanks anyway 😋"

I remember everything.
